# Generated by Django 5.2.8 on 2025-11-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToNaBes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
